#!/usr/bin/env bash

if [ "$#" -ne 2 ] && [ "$#" -ne 3 ]; then
	echo "usage: progress current goal [len]"
	echo -e "\t current: \tcurrent value"
	echo -e "\t goal: \tpages goal"
	echo -e "\toptional:"
	echo -e "\tlen: \tprogress bar length (default=80)"
	exit 0
fi

current=$1
goal=$2

if [ "$#" -eq 3 ]; then
	len=$3
else
	len=80
fi

# A=$("scale=2; `detex -n $CO-[01]*.tex | wc -c`/1800;" | bc)
# lines=$(detex -n $current | wc -c)

# double_lines=$(echo 'scale=2; '$lines | bc)

# rate=$(($lines))
blank=$(($goal - $current))
echo $blank
echo $goal

if [ $blank -le 0 ]; then
	current=$goal
	blank=0
fi
echo $blank

double_current=$(echo 'scale=2; '$current | bc)

percent=$(echo 'scale=2; '$double_current'*100/'$goal | bc)
p=$(echo 'scale=2; '$len'/'$goal'*'$double_current | bc)
full=$(echo $p | awk '{print int($0)}')
empty=$(($len-$full))
echo "full"
echo $full
echo "empty"
echo $empty

printf "|"
printf "%0.s▇" `seq 0 $(($full - 1))`

printf "%0.s_" `seq 0 $(($empty - 1))`

printf "| %s/%0.2f  %s%%\n" "$double_current" "$goal" "$percent"
